let notes = [ // picture number + 2 = line number
  '',
  'what are these pants called',
  '',
  'get rid of thy anxiety!',
  'uhh favor? i mean, favor? i mean, favor? i mean, ',
  '',
  'we forgor sometimes, is okie dokie',
  '',
  '',
  'this is kelly nichols!',
  '',
  'the dubious box my brain opens when it\'s sleepy time:',
  'SOMEONE IS STRANGE',
  '',
  'oh my god those eyes are captivating',
  'bombastic front eye',
  '',
  'propoganda is a scam by big fear to sell more radicalism',
  '',
  'm y   b o n e   c o l l e c t i o n',
  '1-800-EAT-SHIT',
  '',
  'if i were into 2d, i would too',
  'kibby',
  '',
  't\'is golden hour, m\'lord',
  'the hair is everything!!!!!!!!!!!!!',
  '',
  'people don\'t think it be like it be, but it do',
  '',
  'god forbid a woman take charge',
  '',
  'me',
  '',
  '',
  'god i wish that were me',
  'french revolutionary',
  '',
  'remember children, it costs nothing to be nice',
  'step into my office',
  '',
  '',
  'my crush',
  'help!!! what did you do to my hash brown!!!',
  'ok wait where do i look',
  '',
  'chilling on a cliff~',
  '',
  'you are not someone else\'s goals',
  '',
  '',
  'FREE ME, MASTER',
  'i am the right place at the right time',
  '',
  'ok which wizard was this',
  '',
  'geronimo, the crow would be happy to accompany you',
  '',
  '',
  'FUCK THE WACK ASS PEOPLE',
  'i don\'t even have to make a joke',
  'this is ig/jennlacatena!',
  '',
  '',
  'elevator music ahh',
  '',
  'who i\'m tryna be',
  'this is tt/fashionflicks13!',
  '',
  'my original fake-pinterest crush',
  '',
  'bound in the soul and in real life',
  'become so wild that people want to belong with you',
  'M Y   B O N E   C O L L E C T I O N',
  '',
  'and wait why do you have the better background',
  '',
  'p  a  s  t  a',
  'bass players >>>',
  '',
  'howl at the moon',
  '',
  '',
  '',
  '',
  'shit i blinked',
  '(it is mocking you)',
  'you are on your own journey',
  '\"i used to play back in the day\"',
  '',
  'we can now conclude that there are at least two (2) cats',
  '',
  'how to overthrow the nicaraguan government',
  '',
  'chimney',
  'fun fact: cats will mock you as a love language',
  '',
  '\"i don\'t see you in the club\" ok i don\'t see you in the creek',
  '',
  'disclaimer: i haven\'t been in a record shop before',
  '',
  '',
  'autism be damned, my boy can work a grill',
  '',
  'maybe you *can* have shit in detroit',
  '',
  'SO WHAT ???',
  '[distant sounds of stammering]',
  '',
  '',
  '',
  'she\'s so pretty ????',
  'this is ig/kashaimi!',
  '',
  'bean',
  'my gender is a video game and i skipped the tutorial',
  '',
  'my house!',
  'goals frfr',
  '',
  'this turned from a notebook into my obsidian vault',
  'please can i have a hug',
  '',
  'i have no desire for more',
  '',
  'super comfy outfit that i\'m definitely replicating once i move out',
  'super cool outfit',
  'i am also replicating this outfit once i move out too',
  'SO TRUE BESTIE',
  '',
  'this kinda looks like madison beer (kinda)',
  'how to dissapear completely',
  '',
  'this is chuck shuldiner!',
  'all things grow when immersed in love',
  'i got wilbur soot flashbacks',
  '',
  '\"man, i want to sit but like super far up\"; the humble power line:',
  'tights are cool, fishnets are cool, boots are cool',
  '',
  'red boots',
  'i love the buns',
  '',
  '',
  'she slip on my knot',
  'this is tt/maracalli!',
  'men in uniform <3',
  '',
  'the day of reckoning is upon us',
  'let us engage in some tomfoolery',
  '',
  'swing the pain away',
  'the fire lookout of my dreams',
  'pick up, someone\'s calling',
  '',
  '',
  'admiring the flowers',
  '',
  'life is good',
  'oh lawd he thicc',
  'appreciate the shoes not on the bed',
  'born to be a panther, forced to be a housecat',
  '',
  '',
  'he (speak)s in (easy) terms',
  'chwater',
  'the game is telling me to go in the ocean',
  '',
  'where do i get those tights',
  'love, or whatever',
  'THIS IS MY DREAM',
  '',
  'this is djerq!',
  '',
  '',
  'natural 1',
  '',
  'i\'m overwhelmed and don\'t know how to people properly oops',
  '',
  'the cycle of \"talk too much\" and \"don\'t talk enough\"',
  'this outfit is EVERYTHING',
  'a perfect place to confess your love',
  '',
  '',
  'the g in \"waffle house\" stands for the GREATEST OF ALL TIME',
  '',
  'the seat of super comfyness',
  '',
  'oi i\'m trying to smile, not laugh',
  'something something journey not destination',
  '',
  'band name',
  '',
  '',
  'another museum spotted',
  '',
  'charlie chaplain',
  'this is matthew gray gubler!',
  '',
  'did you even play the game',
  'the kindergartenification of society',
  '',
  'this is enough for me',
  'disclaimer: i still haven\'t been in a record shop',
  '',
  'i am my own audience',
  '',
  '',
  'step into my office',
  '',
  '',
  '',
  'take your own!',
  '',
  '',
  'http://tinyurl.com/mvuet',
  '',
  'gosh darnit not the bus too',
  'no mom, i will never meet my \"person\"',
  '',
  'do crime!', // left off here
  'the bee population has been decreasing',
  '',
  'don\'t get lost in the sauce',
  '',
  'bork wench',
  'i also buy souls!',
  '',
  'WHO ARE YOU WHEN YOU\'RE NOT PERFORMING',
  'a mild plant obsession',
  'my wizard tower',
  '',
  '',
  'why go out to natural causes when you can go out to death by microwave power supply',
  'that\'s a lot of ocean out there',
  'darwin ahh ahh',
  'lead your followers into the sea of ___',
  '',
  'store fronts are always so nice',
  'allergies be damned, i\'m going to get a cat',
  '',
  'you either pet the cat or be pet, choose your fate (not exclusive)',
  'oh my gosh the cuck chair looks so beautiful',
  '',
  '',
  'why does this picture feel so familiar',
  'wealth cap please',
  '',
  'WHAT ARE YOU SEARCHING FOR',
  '',
  'i think this is daisy calloway!',
  '',
  'it comes with the occasional goose flying into your windows!',
  'my future apartment better look like this',
  'what are you hunched over for',
  '',
  'the law of diminishing returns is in full effect',
  'sacrifice your honor',
  '',
  'disney princess ahh ahh',
  'man the netflix adaptation is hard',
  '',
  '',
  'NEIL BANGS OUT TUNES',
  '',
  'wook at the wittwe babbyyyyy~',
  '11:06',
  '',
  '',
  'when the spells don\'t work',
  'don\'t talk to me or my son ever again',
  '',
  '',
  'when you have to specify...',
  'this is pt/mcorneliam',
  'this is djerq!',
  '',
  'this is pt/terezavetriskova',
  '',
  'me to my therapist',
  '',
  '\\m/',
  '',
  'мечта',
  'smart enough to know not to, dumb enough to do it anyway',
  '',
  '',
  'this is lexi jayde!',
  'when they love each other:',
  '',
  'just one kiss',
  'this is pt/v0luharica!',
  '',
  'too many damn record shops',
  '¡VIVA A SEALAND!',
  '',
  '',
  'elevator music',
  'why does someone need NINE DISPLAYS',
  '',
  '',
  'choker ties are NOT worth $10',
  '',
  'i   l o v e   c a t s',
  'patch adams',
  'BASS >>>>>>',
  '',
  'goals',
  'WHAT DO YOU REPRESENT',
  '',
  'this is tt/laferocejo!',
  '',
  'who opened the hell portal',
  '',
  'buff women >>>>>',
  '',
  'you have the option of exploring infinity, and you choose scrolling to infinity',
  'this is ig/ivyhowelll!',
  '',
  '',
  'bah!',
  'you have the aux cord',
  '',
  'this is enough for me, anyway',
  'fuck you life',
  '',
  '',
  '',
  'unz unz unz unz unz unz unz unz',
  'books make really bad pillows',
  'waffle house is THE GREATEST OF ALL TIME',
  '',
  '',
  'good morning jehesus',
  'god forbid a woman do anything',
  '*continues to tresspass*',
  '',
  'i love this outfit',
  'living his best life',
  '',
  'this picture was originally upside-down',
  '',
  '',
  'maybe some more kissing',
  'achievement get: how did we get here?',
  '',
  '',
  '',
  'there is no such thing as too much dice',
  'new first date location just dropped',
  '',
  '',
  'WHO IS SHE, INTERNET PLEASE TELL ME',
  'perfect for a night in',
  '',
  '',
  'layering tank tops over long sleeves is SO CUTE',
  'BASS BASS BABY',
  '',
  'fairy hunting',
  '',
  '!!! BANGER ALERT !!!',
  '',
  'a non-ai picture??? that looks this good???',
  'this is ig/kashaimi!',
  'frirar laurence to romeo:',
  '',
  'I WANT THIS HAIR',
  '',
  'medeival peasant ahh ahh',
  '',
  'god i wish that were me- wait what?',
  '',
  'this is tt/norafawn!',
  '',
  '',
  'consider yourself lucky to have a room with two floors',
  '',
  'YOU THERE',
  'the engineering of crows',
  'i need one of these fr fr',
  '',
  '',
  'the local bard hoppingin when a tune is being played:',
  'we get that you can touch your toes',
  '',
  'forget about the past, forget about the future (somewhat)',
  'she could fix me',
  '',
  '',
  'fionna and cake <3',
  'did you want some plants with your piano?',
  '',
  'how are y\'all affording these two floor rooms',
  '',
  'supervise deez nuts',
  '',
  '',
  '*punches you consentually*',
  'this is albert camus!',
  '',
  'bar of a mob boss',
  '',
  'i need to dress better, getting this suit will start my new wardrobe',
  '',
  'dawn of the last morning',
  '',
  '',
  '',
  'minor plant addiction',
  '!!!!!!!',
  '',
  'how do you get any cooking done, i just wanna look at this',
  '',
  '',
  'this is my 13th reason',
  '',
  'HANDCUFFED TO MY CRUSH (GONE RIGHT) (NOT CLICKBAIT)',
  '',
  '',
  'this is tt/atkoutfit!',
  '',
  'a fire lookout could fix me',
  'rummy',
  '',
  'where\'s my metalhead bf',
  '',
  'elevator music',
  '',
  '',
  '',
  'schrödinger is rolling around in his grave',
  'some statues have fully intact penises',
  '',
  '',
  'the world\'s smallest cafe',
  'THIS IS SO COOL',
  '',
  '',
  'god women are so pretty',
  '',
  '',
  'red tights >>>>>>>',
  'red tights >>>>>>>',
  '',
  '',
  'god forbid a woman read',
  'free will',
  'SHE WILL FIX ME',
  'you will be <strikethrough>okay</strikethrough> gay',
  '',
  '',
  'shit',
  'this is rae cambra!',
  '',
  '',
  'this was a thrift store find on reddit',
  ''
];

var DATABASE = `GO BACK
  LINK : ../index.html
  TYPE : article
${

(() => {
let arr = [];

function formatI(i) {
  if(i.length > 4) { return null; }
  return `${ '0'.repeat(4 - i.toString().length) }${ i }`
}

for(let i = 0; i <= 457; i++) {
  arr[i] = `
${ formatI(i) }
  TYPE : image
  FILE : ${ formatI(i) }.jpg${ notes[i].length > 0 ? `
  NOTE : ${ notes[i] } 
  ` : '' }
`
}

for (let i = arr.length - 1; i > 0; i--) {
  const j = Math.floor(Math.random() * (i + 1));
  [arr[i], arr[j]] = [arr[j], arr[i]];
}

// arr.length = 150 + Math.floor(Math.random() * 50);
console.log(notes.length);
return arr.join('\n');

})()
}
`;

/*

// use this block between the for statement and [return arr] to sort from 0 to whatever
arr = arr.sort((a, b) => {
  const numA = parseInt(a.match(/FILE\s*:\s*(\d+)\.jpg/)[1], 10);
  const numB = parseInt(b.match(/FILE\s*:\s*(\d+)\.jpg/)[1], 10);
  return numA - numB;
});

*/